# Generated by Django 2.1.7 on 2019-02-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20190228_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.CharField(blank=True, help_text='theme css', max_length=255),
        ),
    ]
