# Generated by Django 2.1.7 on 2019-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='study',
            field=models.BooleanField(null=True, verbose_name='Has study spaces'),
        ),
    ]
