# Generated by Django 2.1.7 on 2019-02-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190215_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='open24x7',
            field=models.BooleanField(default=False, verbose_name='Open 24x7'),
        ),
    ]
