# Generated by Django 2.1.7 on 2019-02-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_locationpage_open24x7'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured location'),
        ),
    ]
