# Generated by Django 2.1.7 on 2019-02-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_socialmediasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
